### ISSUE TITLE
Quick region server swap

### ISSUE THREAD

**Issue by ELChris414** [LEGOlord208/DiscordConsole#13]
A command that (of course if you have the required permissions) swaps the region of the current guild. Useful maybe for cron jobs.

**Comment by LEGOlord208** [comment]
Cool idea! Any ideas for syntax? ;)

**Comment by ELChris414** [comment]
serverRegion (set/list/current) [region]

**Comment by LEGOlord208** [comment]
I'll see what I can do ;)

**Comment by ELChris414** [comment]
Cool!

**Comment by ELChris414** [comment]
Cool! That was quick!
