### ISSUE TITLE
Move away from C code

### ISSUE THREAD

**Issue by ELChris414** [LEGOlord208/DiscordConsole#14]
I know you already have this planned, but I am making an issue just so it exists as a Milestone maybe. Move away from that sql library that uses C code for easier building without many 3rd party libraries to connect Go with C

**Comment by LEGOlord208** [comment]
Thinking about this myself. But token detection relies on it. Unless I make some external executable, I think that I will be forced to keep it.

**Comment by LEGOlord208** [comment]
Fixed in the develop branch
