### ISSUE TITLE
Sending message without "say"

### ISSUE THREAD

**Issue by qiwichupa** [LEGOlord208/DiscordConsole#20]
Hi. Thank you for this lighweight client, but please, give us more standard format for commands, like /commandname. At least for sending messages, because it is not comfortable now to type "say" before every message, especially when message written with non-latin symbols.

**Comment by Mnpn03** [comment]
Using no prefix is a standard format for "terminal" type applications.

**Comment by LEGOlord208** [comment]
Maybe having some form of toggle would be better? `togglechat` to toggle chat mode?

**Comment by qiwichupa** [comment]
That is good idea!

**Comment by Mnpn03** [comment]
How about another text colour to indicate chat mode? Light blue?

**Comment by LEGOlord208** [comment]
I will work on it later today.

**Comment by LEGOlord208** [comment]
Added in the latest develop.
Looks like this:

![image](https://cloud.githubusercontent.com/assets/12830969/25242013/6578c848-25f8-11e7-8e34-3044944eb85f.png)
