### ISSUE TITLE
Exit on login

### ISSUE THREAD

**Issue by Mnpn03** [LEGOlord208/DiscordConsole#22]

**Comment by Mnpn03** [comment]
Derp^

When typing exit on login it errors (ofc it's no token). Make it easier and just exit instead.

**Comment by LEGOlord208** [comment]
Not sure about this. Remember about Ctrl+D. That always works :smile:

**Comment by Mnpn03** [comment]
Small changes make perfect!

**Comment by LEGOlord208** [comment]
There are a bunch of dialog boxes. I can't make them all have `exit` as a command. And it would break if somebody actually had `exit` as password or something.
