### ISSUE TITLE
Being able to change the prefix

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [LEGOlord208/DiscordConsole#23]
~~`console.` is way too fucking long so change this fucking bullshit else I'll have to call my mom~~

Would it be possible to edit the prefix in any way so I don't waste my very important time typing `console.` instead of `c.`? kthx

**Comment by LEGOlord208** [comment]
Not sure about this one. I'll call on the community to decide.

**Comment by LEGOlord208** [comment]
Added in the latest develop
