### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [LEGOlord208/DiscordConsole#26]
`console.alias "Old command here" "New command"`
 A good example would be with run command.

From `console.run my_big_file.lua` you could just do `console.alias "run my_big_file.lua" "prank"` and then just do `console.prank`

**Comment by Mnpn03** [comment]
If I want to change "console.big" to "console.run"? Also this could be abused: "console.fuck your mom" instead of big.

**Comment by LEGOlord208** [comment]
Remember it only changes locally. The only one you abuse by that is yourself @Mnpn03

**Comment by LEGOlord208** [comment]
Follow up question: How would you remove an alias?

**Comment by Doyouwanttomakeacake** [comment]
Well.. I guess you'ld type `console.alias "The alias"` and it would revert back to the classic command. If done with `console.alias "Default command"` it won't allow users to have multiple alias for one command. 

So yeah, either just type the alias  w/o the command or add subcommands.


`alias list`
`alias add` 
`alias remove`

**Comment by LEGOlord208** [comment]
Yep, added in develop
