### ISSUE TITLE
One message, two commands.

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [LEGOlord208/DiscordConsole#31]
Being able to execute multiple commands in one message.

[https://i.imgur.com/DL6sSiG.png](image)

y0

**Comment by LEGOlord208** [comment]
That would be dangerous for scripts and such.

**Comment by LEGOlord208** [comment]
Actually no, let's have a vote on it. I could always disable it for scripts I guess...

**Comment by LEGOlord208** [comment]
That was unecessary.

**Comment by Mnpn03** [comment]
Object. Can be abused alot; "console.quote {} console.quote {} console.quote {} console.quote {}" etc. I also generally do not like the idea.

Also would this be hard to implement?

**Comment by ELChris414** [comment]
A big fat no. Sorry pal, but this is unnecessary stuff that will take a lot of work, and will slow the program down even for simple commands because of the checks for another valid one. Its just not a good idea.
