### ISSUE TITLE
Weird Shortcuts?

### ISSUE THREAD

**Issue by Tehcatninja** [legolord208/DiscordConsole#33]
For some reason when i press backspace it deletes an entire word, when i press F it wont write anything same thing for D, How can i fix this? Im on version 2.3 aswell

**Comment by legolord208** [comment]
This is a problem with an upstream repository. See https://github.com/chzyer/readline/issues/68.

It's caused by Windows and Alt+Tab, so... I'm afraid you have to press Alt once again to disable it.

**Comment by Tehcatninja** [comment]
Thanks!
