### ISSUE TITLE
nickall not working

### ISSUE THREAD

**Issue by spelled-ayayron** [LEGOlord208/DiscordConsole#51]
I can't use nickall with either my user token or a webhook token. I'm getting an HTTP 403 for the user token, while the webhook just doesn't have access at all. I'm trying to clear all the nicknames in my server and I'm not sure what I should be doing to achieve that when I stumbled upon this. What should I do?

**Comment by Mnpn** [comment]
It looks like Discord has changed their API about getting all members for privacy reasons (see [issue #820 in discordgo](https://github.com/bwmarrin/discordgo/issues/820)) which has subsequently broken both `members` and `nickall`. [Here's Discord's information about this](https://discord.com/developers/docs/topics/gateway#privileged-intents). 

As for how to resolve this, you can create a bot and toggle a setting called "Privileged Intents" for server members, which should let you use `nickall` with it in DiscordConsole. Not sure how user tokens will be able to handle this, my guess is that they just won't be able to, which really sucks.

As for webhooks, they have no such permissions. They can only really chat. (See the `help` command when logged in as one)

**Comment by spelled-ayayron** [comment]
I see, thank you for the information and I will look into setting that up.
