### ISSUE TITLE
Channel management

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [LEGOlord208/DiscordConsole#6]
```
Channeladd <Name> [ID of the role if restricting to one role]
```
```
Channeldelete ID
```
```
Channeledit <ID> [Position/Perms of a role (ID)/Name]
```

**Comment by Doyouwanttomakeacake** [comment]
Oh, and the same commands but with `VChannel..` for voice channels. 
VChanneledit would include Bitrate & members limit.

**Comment by ELChris414** [comment]
Don't really see the reason, but sure, that's easily implemented.

**Comment by LEGOlord208** [comment]
I really can't decide about this one.

**Comment by ELChris414** [comment]
Is it really required to cover 100% of the API? That's the way I see it that if this functionality exists in Discord Console it just makes the project a trial to cover 100% of the API

**Comment by LEGOlord208** [comment]
My thoughts too.

Yeah, I think I'll close this one for now.
