### ISSUE TITLE
More options for the invite.

### ISSUE THREAD

**Issue by Doyouwanttomakeacake** [LEGOlord208/DiscordConsole#8]
`invite accept [code]` - Accept an invite
`invite create [flags]`

List of flags :  
GUILD_ID (If non selected, default to the current guild)
CHANNEL_ID (If non selected, default to the current channel)
Expiration (In minutes. If non selected default to Never.)
Uses (Maxium number of uses. If non select default to No limit)
Membership (Default to "false". If set to "true" enable the Temporary Membership system.)
All flags are separated by a /

**Comment by LEGOlord208** [comment]
There are already  
`invite` and  
`invite [code]`.

I don't wanna break anything but... I'll look into it

**Comment by LEGOlord208** [comment]
Solved in DiscordConsole 2.0.0dev.
