### ISSUE TITLE
Different languages

### ISSUE THREAD

**Issue by Mnpn03** [LEGOlord208/DiscordConsole#9]
Implement different IRL languages that can be set at startup with an argument; example: "discordconsole.exe --noupdate --lang en"

Then in DiscordConsole when a user runs the command "languages" it lists the available ones.

Yah or Nah?

**Comment by ELChris414** [comment]
I sure can do a greek translation, but make sure for UTF-8 support! :P

**Comment by LEGOlord208** [comment]
Fixed in fae5611b809637da5a20d154f9a4b620288c07ac
